version: "3"

services:
  jupyter:
    image: jupyter:x86_64-python-3.11
    build:
      context: ./src/infra/jupyter/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./docs:/home/jovyan/work
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

networks:
  default:
    name: jupyter
